log_level = "re"
path_map = "随便"
[mysql]
  bool = true
  host = "yourhost"
  name = "yourname"
  password = "yourpassword"
  user = "youruser"

[redis]
  port = 3306

[time]
  a = "2020-12-13 02:20:03"
  d = "40ms"
