// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/18211167516/go-lib/demo/zerodemo/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{

			
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: ZerodemoHandler(serverCtx),
			},
		},
	)
}
